# Generated by Django 3.2.6 on 2021-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='Helsinki', max_length=20),
            preserve_default=False,
        ),
    ]
