# Generated by Django 3.2.6 on 2021-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.FloatField(),
        ),
    ]
