# Generated by Django 3.2.6 on 2021-09-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_worldborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
