# Generated by Django 3.2.6 on 2021-09-01 08:50

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
