# Generated by Django 3.2.6 on 2021-09-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_station_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='location',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='station',
            name='x',
        ),
        migrations.RemoveField(
            model_name='station',
            name='y',
        ),
    ]
